### PR TITLE
Bentley OBD connector

### PR DESCRIPTION
**Pull request by tlmnrnhrdt**
Hi,

i added a bit of documentation for the latest features regarding simple walls, slabs, columns, beams, etc. in the OBD connector.
Please add once you merged from the arup-group repo.

Cheers,
Tilman

### CODE REVIEW

**Comment by clairekuang** [comment]
We haven't aligned since the initial merge, so there is definitely a bit of work to do especially for OBD! @tlmnrnhrdt are you available for a brief meeting to go over changes in both repos? (We have a few big ones in ours, eg adding DUI2)

**Comment by tlmnrnhrdt** [comment]
> We haven't aligned since the initial merge, so there is definitely a bit of work to do especially for OBD! @tlmnrnhrdt are you available for a brief meeting to go over changes in both repos? (We have a few big ones in ours, eg adding DUI2)

Hi @clairekuang, yes I am available from next Wednesday onward. I think your changes regarding DUI2 should be already incorporated. But let´s have a look together next week :)

**Comment by teocomi** [comment]
Just noticed this is still open! Should it be merged?

**Comment by tlmnrnhrdt** [comment]
> Just noticed this is still open! Should it be merged?

Only after we have aligned our repos, planning to do this from next week onward :)

**Comment by teocomi** [comment]
Closing as stale, let's reopen when merged from arup!

**Pull request closed without merging**
